import archiver from "archiver";
import type { Archiver } from "archiver";
import { Readable } from "stream";
import type { CodeFramework } from "./codeGenerators";
import { getFrameworkDependencies } from "./codeGenerators";

interface ProjectExportOptions {
  projectName: string;
  code: string;
  framework: CodeFramework;
  description: string;
  includeTypeScript: boolean;
}

/**
 * Generate package.json for the project
 */
function generatePackageJson(
  projectName: string,
  framework: CodeFramework,
  includeTypeScript: boolean
): object {
  const deps = getFrameworkDependencies(framework, includeTypeScript);

  const scripts: Record<string, string> = {
    dev: "vite",
    build: "vite build",
    preview: "vite preview",
  };

  if (framework === "angular") {
    scripts.dev = "ng serve";
    scripts.build = "ng build";
  } else if (framework === "vue" && includeTypeScript) {
    scripts.build = "vue-tsc && vite build";
  }

  return {
    name: projectName.toLowerCase().replace(/\s+/g, "-"),
    version: "1.0.0",
    description: "Generated by PixelCraft",
    type: "module",
    scripts,
    dependencies: deps,
    devDependencies: {
      vite: "^7.0.0",
      "@vitejs/plugin-react": "^5.0.0",
      ...(includeTypeScript && {
        typescript: "^5.0.0",
        "@types/node": "^20.0.0",
      }),
    },
  };
}

/**
 * Generate README.md for the project
 */
function generateReadme(
  projectName: string,
  framework: CodeFramework,
  description: string
): string {
  const frameworkName = {
    react: "React",
    vue: "Vue 3",
    angular: "Angular",
    svelte: "Svelte",
    html: "HTML/CSS/JS",
    nodejs: "Node.js/Express",
    python: "Python/Flask",
    php: "PHP/Laravel",
    java: "Java/Spring Boot",
    csharp: "C#/.NET Core",
  }[framework];

  return `# ${projectName}

Generated by [PixelCraft](https://pixelcraft.app)

## Description

${description}

## Framework

Built with **${frameworkName}**

## Getting Started

### Prerequisites

- Node.js 16+ 
- npm or pnpm

### Installation

\`\`\`bash
# Install dependencies
npm install
# or
pnpm install
\`\`\`

### Development

\`\`\`bash
npm run dev
# or
pnpm dev
\`\`\`

The application will be available at \`http://localhost:5173\`

### Build

\`\`\`bash
npm run build
# or
pnpm build
\`\`\`

### Preview

\`\`\`bash
npm run preview
# or
pnpm preview
\`\`\`

## Project Structure

\`\`\`
${projectName}/
├── src/
│   ├── main.tsx          # Application entry point
│   ├── App.tsx           # Main component
│   ├── components/       # Reusable components
│   ├── pages/            # Page components
│   └── styles/           # Global styles
├── public/               # Static assets
├── package.json          # Project dependencies
├── vite.config.ts        # Vite configuration
└── tsconfig.json         # TypeScript configuration
\`\`\`

## Features

- ⚡ Fast development with Vite
- 🎨 Tailwind CSS for styling
- 📱 Responsive design
- ♿ Accessible components
- 🔒 Type-safe with TypeScript

## Deployment

### Vercel

\`\`\`bash
npm install -g vercel
vercel
\`\`\`

### Netlify

\`\`\`bash
npm install -g netlify-cli
netlify deploy
\`\`\`

### GitHub Pages

\`\`\`bash
npm run build
# Deploy the dist/ folder
\`\`\`

## License

MIT

## Support

For issues and questions, visit [PixelCraft Support](https://pixelcraft.app/support)

---

**Generated on:** ${new Date().toISOString()}
`;
}

/**
 * Generate .gitignore file
 */
function generateGitignore(): string {
  return `# Dependencies
node_modules/
/.pnp
.pnp.js

# Testing
/coverage

# Production
/dist
/build

# Misc
.DS_Store
*.pem

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Local env files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
Thumbs.db
`;
}

/**
 * Generate tsconfig.json for TypeScript projects
 */
function generateTsConfig(): object {
  return {
    compilerOptions: {
      target: "ES2020",
      useDefineForClassFields: true,
      lib: ["ES2020", "DOM", "DOM.Iterable"],
      module: "ESNext",
      skipLibCheck: true,
      esModuleInterop: true,
      allowSyntheticDefaultImports: true,
      strict: true,
      noImplicitAny: true,
      strictNullChecks: true,
      strictFunctionTypes: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noImplicitReturns: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      jsx: "react-jsx",
      baseUrl: ".",
      paths: {
        "@/*": ["src/*"],
      },
    },
    include: ["src"],
    references: [{ path: "./tsconfig.node.json" }],
  };
}

/**
 * Generate vite.config.ts
 */
function generateViteConfig(framework: CodeFramework): string {
  let plugins = "";

  switch (framework) {
    case "react":
      plugins = `import react from '@vitejs/plugin-react'
export default {
  plugins: [react()],`;
      break;
    case "vue":
      plugins = `import vue from '@vitejs/plugin-vue'
export default {
  plugins: [vue()],`;
      break;
    case "svelte":
      plugins = `import svelte from 'vite-plugin-svelte'
export default {
  plugins: [svelte()],`;
      break;
    default:
      plugins = `export default {`;
  }

  return `import { defineConfig } from 'vite'
import ${plugins}
  resolve: {
    alias: {
      '@': '/src',
    },
  },
  server: {
    port: 5173,
    open: true,
  },
  build: {
    outDir: 'dist',
    sourcemap: false,
    minify: 'terser',
  },
}
`;
}

/**
 * Generate main.tsx entry point
 */
function generateMainTsx(framework: CodeFramework): string {
  if (framework === "react") {
    return `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`;
  } else if (framework === "vue") {
    return `import { createApp } from 'vue'
import App from './App.vue'
import './style.css'

createApp(App).mount('#app')
`;
  } else if (framework === "svelte") {
    return `import App from './App.svelte'
import './app.css'

const app = new App({
  target: document.getElementById('app')!,
})

export default app
`;
  }

  return `// Main entry point
console.log('App started')
`;
}

/**
 * Generate index.html
 */
function generateIndexHtml(projectName: string, framework: CodeFramework): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

/**
 * Create a ZIP file with the complete project structure
 */
export async function createProjectZip(
  options: ProjectExportOptions
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const archive = archiver("zip", {
      zlib: { level: 9 },
    });

    const chunks: Buffer[] = [];

    archive.on("data", (chunk: Buffer) => {
      chunks.push(chunk);
    });

    archive.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    archive.on("error", (err: Error) => {
      reject(err);
    });

    try {
      // Add project root files
      archive.append(
        JSON.stringify(
          generatePackageJson(options.projectName, options.framework, options.includeTypeScript),
          null,
          2
        ),
        { name: "package.json" }
      );

      archive.append(generateReadme(options.projectName, options.framework, options.description), {
        name: "README.md",
      });

      archive.append(generateGitignore(), {
        name: ".gitignore",
      });

      archive.append(JSON.stringify(generateTsConfig(), null, 2), {
        name: "tsconfig.json",
      });

      archive.append(generateViteConfig(options.framework), {
        name: "vite.config.ts",
      });

      archive.append(generateIndexHtml(options.projectName, options.framework), {
        name: "index.html",
      });

      // Add src directory
      archive.append(options.code, {
        name: `src/App.${options.framework === "vue" ? "vue" : options.framework === "svelte" ? "svelte" : "tsx"}`,
      });

      archive.append(generateMainTsx(options.framework), {
        name: "src/main.tsx",
      });

      archive.append(
        `@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: 'Inter', sans-serif;
  background-color: #f9fafb;
  color: #111827;
}

#root {
  min-height: 100vh;
}
`,
        { name: "src/index.css" }
      );

      // Add public directory
      archive.append("", { name: "public/.gitkeep" });

      // Finalize the archive
      archive.finalize();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Get file extension for exported code
 */
export function getExportFileExtension(framework: CodeFramework): string {
  switch (framework) {
    case "vue":
      return ".vue";
    case "svelte":
      return ".svelte";
    case "angular":
      return ".ts";
    case "react":
    default:
      return ".tsx";
  }
}

/**
 * Generate project filename
 */
export function generateProjectFilename(projectName: string): string {
  return `${projectName.toLowerCase().replace(/\s+/g, "-")}-pixelcraft.zip`;
}
