import { z } from "zod";
import { protectedProcedure, router } from "./_core/trpc";
import { createProjectZip, generateProjectFilename } from "./exportService";
import type { CodeFramework } from "./codeGenerators";

export const exportRouter = router({
  // Export project as ZIP
  exportProject: protectedProcedure
    .input(
      z.object({
        projectName: z.string().min(3, "Project name must be at least 3 characters"),
        code: z.string().min(10, "Code must be at least 10 characters"),
        framework: z.enum(["react", "vue", "angular", "svelte", "html"]),
        description: z.string().optional(),
        includeTypeScript: z.boolean().default(true),
      })
    )
    .mutation(async ({ input, ctx }) => {
      try {
        // Check subscription for download
        const { getUserSubscription } = await import("./db");
        const subscription = await getUserSubscription(ctx.user.id);

        // Free users cannot export
        if (!subscription || !subscription.subscription_plans || subscription.subscription_plans.name === "free") {
          return {
            success: false,
            error: "Upgrade to export projects",
          };
        }

        const zipBuffer = await createProjectZip({
          projectName: input.projectName,
          code: input.code,
          framework: input.framework as CodeFramework,
          description: input.description || "Generated by PixelCraft",
          includeTypeScript: input.includeTypeScript,
        });

        return {
          success: true,
          filename: generateProjectFilename(input.projectName),
          size: zipBuffer.length,
          data: zipBuffer.toString("base64"),
        };
      } catch (error) {
        console.error("[Export] Error:", error);
        return {
          success: false,
          error: error instanceof Error ? error.message : "Failed to export project",
        };
      }
    }),

  // Get export formats
  getFormats: protectedProcedure.query(() => {
    return [
      {
        id: "zip",
        name: "ZIP Archive",
        description: "Complete project with all files",
        icon: "📦",
      },
      {
        id: "github",
        name: "GitHub",
        description: "Push directly to GitHub (coming soon)",
        icon: "🐙",
        disabled: true,
      },
      {
        id: "codesandbox",
        name: "CodeSandbox",
        description: "Open in CodeSandbox (coming soon)",
        icon: "⚙️",
        disabled: true,
      },
    ];
  }),

  // Get export options
  getOptions: protectedProcedure.query(() => {
    return {
      includeReadme: true,
      includeGitignore: true,
      includeTypeScript: true,
      includeDevDependencies: true,
      minifyCode: false,
    };
  }),

  // Validate export
  validate: protectedProcedure
    .input(
      z.object({
        projectName: z.string(),
        code: z.string(),
        framework: z.enum(["react", "vue", "angular", "svelte", "html"]),
      })
    )
    .query(({ input }) => {
      const errors: string[] = [];

      // Validate project name
      if (input.projectName.length < 3) {
        errors.push("Project name must be at least 3 characters");
      }
      if (!/^[a-zA-Z0-9\s\-_]+$/.test(input.projectName)) {
        errors.push("Project name can only contain letters, numbers, spaces, hyphens, and underscores");
      }

      // Validate code
      if (input.code.length < 10) {
        errors.push("Code must be at least 10 characters");
      }

      return {
        isValid: errors.length === 0,
        errors,
      };
    }),

  // Get export status
  getStatus: protectedProcedure.query(async ({ ctx }) => {
    try {
      const { getUserSubscription } = await import("./db");
      const subscription = await getUserSubscription(ctx.user.id);

      const tier = subscription?.subscription_plans?.name || "free";
      return {
        canExport: subscription && tier !== "free",
        tier,
        message:
          !subscription || tier === "free"
            ? "Upgrade to export projects"
            : "You can export projects",
      };
    } catch (error) {
      return {
        canExport: false,
        tier: "free",
        message: "Unable to check export status",
      };
    }
  }),
});
